### ISSUE TITLE
ecomm_pvalue has been replaced by ecomm_totalvalue

### ISSUE THREAD

**Issue by matt1** [mobweb/MobWeb_AdWordsRemarketingTags#1]
Hi there,

The https://developers.google.com/adwords-remarketing-tag/parameters site was recently updated. 

The ecomm_pvalue parameter on product pages has been replaced by ecomm_totalvalue (so ecomm_totalvalue is now applicable for product, cart and purchase pages).

Thanks

**Comment by mobweb** [comment]
Thanks for the heads up, I will look into this ASAP.

**Comment by mobweb** [comment]
Fixed here: https://github.com/mobweb/MobWeb_AdWordsRemarketingTags/commit/687152a34c77c9bbbd9b84981ad2cc55f406b88a
